### ISSUE TITLE
java.lang.NoClassDefFoundError: com.chibatching.kotpref.KotprefPreferences$KotprefEditor$apply$1

### ISSUE THREAD

**Issue by ligi** [chibatching/Kotpref#43]
After updating to kotpref 2.1.0 and Kotlin 1.1.1 my UI-Tests fail with:

```
E/AndroidRuntime( 7659): Process: org.ligi.gobandroid_hd, PID: 7659
E/AndroidRuntime( 7659): java.lang.NoClassDefFoundError: com.chibatching.kotpref.KotprefPreferences$KotprefEditor$apply$1
E/AndroidRuntime( 7659): 	at com.chibatching.kotpref.KotprefPreferences$KotprefEditor.apply(KotprefPreferences.kt:21)
E/AndroidRuntime( 7659): 	at com.chibatching.kotpref.KotprefModel.commitBulkEdit(KotprefModel.kt:199)
E/AndroidRuntime( 7659): 	at org.ligi.gobandroid_hd.ui.game_setup.GameSetupFragment.refresh_ui(GameSetupFragment.kt:151)
E/AndroidRuntime( 7659): 	at org.ligi.gobandroid_hd.ui.game_setup.GameSetupFragment.onProgressChanged(GameSetupFragment.kt:80)
E/AndroidRuntime( 7659): 	at android.widget.SeekBar.onProgressRefresh(SeekBar.java:91)
E/AndroidRuntime( 7659): 	at android.widget.ProgressBar.doRefreshProgress(ProgressBar.java:655)
E/AndroidRuntime( 7659): 	at android.widget.ProgressBar.refreshProgress(ProgressBar.java:667)
E/AndroidRuntime( 7659): 	at android.widget.ProgressBar.setProgress(ProgressBar.java:714)
E/AndroidRuntime( 7659): 	at android.widget.ProgressBar.setProgress(ProgressBar.java:695)
E/AndroidRuntime( 7659): 	at org.ligi.gobandroid_hd.ui.game_setup.GameSetupFragment.refresh_ui(GameSetupFragment.kt:109)
E/AndroidRuntime( 7659): 	at org.ligi.gobandroid_hd.ui.game_setup.GameSetupFragment.onProgressChanged(GameSetupFragment.kt:80)
E/AndroidRuntime( 7659): 	at android.widget.SeekBar.onProgressRefresh(SeekBar.java:91)
E/AndroidRuntime( 7659): 	at android.widget.ProgressBar.doRefreshProgress(ProgressBar.java:655)
E/AndroidRuntime( 7659): 	at android.widget.ProgressBar.refreshProgress(ProgressBar.java:667)
E/AndroidRuntime( 7659): 	at android.widget.ProgressBar.setProgress(ProgressBar.java:714)
E/AndroidRuntime( 7659): 	at android.widget.ProgressBar.setProgress(ProgressBar.java:695)
E/AndroidRuntime( 7659): 	at org.ligi.gobandroid_hd.ui.game_setup.GameSetupFragment.refresh_ui(GameSetupFragment.kt:105)
E/AndroidRuntime( 7659): 	at org.ligi.gobandroid_hd.ui.game_setup.GameSetupFragment.onStart(GameSetupFragment.kt:66)
E/AndroidRuntime( 7659): 	at android.support.v4.app.Fragment.performStart(Fragment.java:2218)
E/AndroidRuntime( 7659): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1340)
E/AndroidRuntime( 7659): 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
E/AndroidRuntime( 7659): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
E/AndroidRuntime( 7659): 	at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:2907)
E/AndroidRuntime( 7659): 	at android.support.v4.app.FragmentController.dispatchStart(FragmentController.java:212)
E/AndroidRuntime( 7659): 	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:613)
E/AndroidRuntime( 7659): 	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
E/AndroidRuntime( 7659): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
E/AndroidRuntime( 7659): 	at android.app.Activity.performStart(Activity.java:5241)
E/AndroidRuntime( 7659): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2168)
E/AndroidRuntime( 7659): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
E/AndroidRuntime( 7659): 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
E/AndroidRuntime( 7659): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
E/AndroidRuntime( 7659): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 7659): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 7659): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
E/AndroidRuntime( 7659): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 7659): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 7659): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
E/AndroidRuntime( 7659): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
E/AndroidRuntime( 7659): 	at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager( 1549): Force-killing crashed app org.ligi.gobandroid_hd at watcher's request
```

will have to digg a bit deeper - but dropping this here now as I guess the root is in kotpref and you might see whats wrong in a glance without digging.

**Comment by chibatching** [comment]
Is this happen on only UI tests? Is your UI tests espresso?

**Comment by ligi** [comment]
yes these are espresso ui tests and it is only happening there
currently. Not really sure what is going on there yet - but it is
reproducable - when I go back to kotlin 1.1.0 and kotpref 2.0.0
everything passes - switching to kotlin 1.1.1 and kotpref 2.1.0 and I
get this problem. If you want to try for your self - this is the code:
https://github.com/ligi/gobandroid

**Comment by chibatching** [comment]
I tried UI test of your project, and failed test with other error below.

```
E/AndroidRuntime: FATAL EXCEPTION: main
        Process: org.ligi.gobandroid_hd, PID: 4958
        java.lang.RuntimeException: Unable to create application org.ligi.gobandroid_hd.TestApp: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4710)
            at android.app.ActivityThread.-wrap1(ActivityThread.java)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5417)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
        Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
            at org.ligi.gobandroid_hd.ui.GoPrefs.getThemeInt(GoPrefs.kt:73)
            at org.ligi.gobandroid_hd.App.onCreate(App.java:41)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
            at android.support.test.runner.MonitoringInstrumentation.callApplicationOnCreate(MonitoringInstrumentation.java:323)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
            at android.app.ActivityThread.-wrap1(ActivityThread.java) 
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
            at android.os.Handler.dispatchMessage(Handler.java:102) 
            at android.os.Looper.loop(Looper.java:148) 
            at android.app.ActivityThread.main(ActivityThread.java:5417) 
            at java.lang.reflect.Method.invoke(Native Method) 
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

I don't know it is the issue of kotpref, but Kotlin 1.1.1 seems having some bugs of androidTest.

- https://youtrack.jetbrains.com/issues/KT?q=androidtest

So, I will investigate it continuously and watch kotlin issues.

Thanks

**Comment by ligi** [comment]
Reading the diff - this might be a fix for the problem : https://github.com/jetbrains/kotlin/commit/132393cc647eacae0d02d623c8fad48c85e2f53f

so it might have been this kotlin problem and just surfaced at kotpref for me - so waiting for 1.1.2 - feel free to close.

**Comment by chibatching** [comment]
I found the cause of this problem. I call java 8 function `Map#forEach` at [KotprefPreference](https://github.com/chibatching/Kotpref/blob/master/kotpref/src/main/kotlin/com/chibatching/kotpref/KotprefPreferences.kt#L21)
I'll fix it as soon as possible. Sorry.

**Comment by ligi** [comment]
Thanks for looking into this! Love this library!!

**Comment by chibatching** [comment]
Fixed this issue in latest version 2.1.1!
Thanks! :)

**Comment by ligi** [comment]
I can confirm that the ClassDefNotFound is fixed in 2.1.1 - thanks! - unfortunately now on another emulator (differend SDK-level)  I a similar NullPointer you mentioned:

```
03-26 19:16:59.602 10300 10313 V NoDialogActivityController: appCrashed: org.ligi.gobandroid_hd:10429 java.lang.NullPointerException java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference java.lang.RuntimeException: Unable to create application org.ligi.gobandroid_hd.TestApp: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
03-26 19:16:59.602 10300 10313 V NoDialogActivityController: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4710)
03-26 19:16:59.602 10300 10313 V NoDialogActivityController: 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
03-26 19:16:59.602 10300 10313 V NoDialogActivityController: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
03-26 19:16:59.602 10300 10313 V NoDialogActivityController: 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-26 19:16:59.602 10300 10313 V NoDialogActivityController: 	at android.os.Looper.loop(Looper.java:148)
03-26 19:16:59.602 10300 10313 V NoDialogActivityController: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
03-26 19:16:59.602 10300 10313 V NoDialogActivityController: 	at java.lang.reflect.Method.invoke(Native Method)
03-26 19:16:59.602 10300 10313 V NoDialogActivityController: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-26 19:16:59.602 10300 10313 V NoDialogActivityController: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
03-26 19:16:59.602 10300 10313 V NoDialogActivityController: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
03-26 19:16:59.602 10300 10313 V NoDialogActivityController: 	at org.ligi.gobandroid_hd.ui.GoPrefs.isTransitionDone(GoPrefs.kt)
03-26 19:16:59.602 10300 10313 V NoDialogActivityController: 	at org.ligi.gobandroid_hd.ui.application.GobandroidSettingsTransition.transition(GobandroidSettingsTransition.java:25)
03-26 19:16:59.602 10300 10313 V NoDialogActivityController: 	at org.ligi.gobandroid_hd.App.onCreate(App.java:30)
03-26 19:16:59.602 10300 10313 V NoDialogActivityController: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
03-26 19:16:59.602 10300 10313 V NoDialogActivityController: 	at android.support.test.runner.MonitoringInstrumentation.callApplicationOnCreate(MonitoringInstrumentation.java:323)
03-26 19:16:59.602 10300 10313 V NoDialogActivityController: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
03-26 19:16:59.602 10300 10313 V NoDialogActivityController: 	... 8 more

```

isTransition looks like this:

`var isTransitionDone: Boolean by booleanPref(default = false)`

not yet sure how this can be null yet

**Comment by chibatching** [comment]
Oh... I'll investigate it :(

**Comment by Tunous** [comment]
@chibatching 
I'm experiencing `NoClassDefFoundError` when using `blockingBulk` on Android 6.0 or lower. I think that similar change to this one in #44 should be also done for `commit` function in the same file.
